### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Naville** [SatanWoo/JSDebugger#1]
IMHO
``README.md``
<del>It's built on top of JavaScriptCore within C level interface which aims to accelerate the bridging process between Objective-C and JavaScript.</del>
It's built on top of JavaScriptCore's C Interface

<del>Excluded from the core functions provided with JSDebugger, we develop plugin mechanism for you to enhance the ability that JSDebugger able to cover.</del>
We've developed ***** the ability of  JSDebugger.

<del>Choose aims to provide your with the ability to access any objects on heaps. The function will search all instances that match the class name you provided exactly and return all found results as an array.</del>
Choose aims to provide you*** on the heap

And many more

**Comment by SatanWoo** [comment]
OK, I got it. Thanks 4 ur advice
