### ISSUE TITLE
Auto reload file failed when modify file in Vim 

### ISSUE THREAD

**Issue by SatanWoo** [SatanWoo/JSDebugger#12]

**Comment by SatanWoo** [comment]
Bugs also found with modifying files in Xcode Editor/TextEditor.

**Comment by Naville** [comment]
Try [facebook/watchman]( https://github.com/facebook/watchman) instead of crafting one by hand? From personal experience that thing seems to work without a problem

**Comment by dzp181** [comment]
在xcode里面编写js，自动刷新好像没用？

**Comment by SatanWoo** [comment]
> 在xcode里面编写js，自动刷新好像没用？

@dzp181 是的，目前这个vnode相关的触发条件确实都有问题，我还在研究。

**Comment by SatanWoo** [comment]
> Try [facebook/watchman](https://github.com/facebook/watchman) instead of crafting one by hand? From personal experience that thing seems to work without a problem

@Naville Thanks, I will try on it

**Comment by SatanWoo** [comment]
c5bec0a34bbb18e34dbd450975253c671875f48e

**Comment by SatanWoo** [comment]
@Naville Checkout my commit, there is an easy solution to solve this problem without importing so big a project made by Facebook
