### ISSUE TITLE
关于那两个计算公式的理解

### ISSUE THREAD

**Issue by 4ch12dy** [SatanWoo/JSDebugger#18]
关于那两个计算公式的解释：
iOS的malloc分配内存的时候会有tiny和small两种region。其中tiny以16B为quantum，small以512B为quantum。并且tiny在32位、64位机器上size分别为496B和1008B。所以，needed <= boundary是在检查分配内存是否小于tiny的size。(needed + 15) / 16 * 16 != size)主要是检查分配大小needed是否为16的倍数。
更多关于苹果堆设计可以看[这里](http://4ch12dy.site/2019/04/01/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3macos-heap/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3macos-heap/)

**Comment by SatanWoo** [comment]
@4ch12dy 感谢，我学习下
